name: Nekaj lepega
favicon: null
layout_spectrum: 0.8797040903009474
typography_spectrum: 0.9128902687225491
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000004'
    - '#de9357'
    - '#e8c37b'
    - '#f4aa9d'
  brandStrength: 0.4399074234534055
  lightness: 0.46738536073826253
  saturation: 0.4972672825679183
  rhythmicContrast: 0.44202386518009007
purpose: []
